name: PlatformIO CI
on:
  workflow_dispatch:
# on: 
#   push:
#     branches:
#       - 'dev'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
              ~/.cache/npm
              ~/.cache/pip
              ~/.platformio/.cache
              ~/.pio
          key: ${{ runner.os }}-pio
              
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
        
      - name: Compile web files
        run: |
            cd ~/tools/webfilesbuilder
            npm i
            node gulp.js
        
      - name: Build SLZB-06 FW
        run: pio run --project-conf=platformio.ini
        #run: pio ci --board=esp32dev --project-conf=platformio.ini # --project-option="build_flags = -I include"
#         env:
#           PLATFORMIO_CI_SRC: "src/main.cpp"
